/****************************************************************************/
/*  INC.H 15 JAN 89                                                         */
/****************************************************************************/

#ifndef _INC_H
#define _INC_H

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <dir.h>

#include "..\common\kbdcode.h"
#include "..\common\const.h"
#include "..\common\cwtype.h"
#include "..\common\proto.h"
#include "proto.h"

#endif /* _INC_H */
