#
# makefile for cufont.exe
# Written by: Suttipong Kanakakorn
#             Fri  08-25-1989  21:38:46
#

!include "..\config.mak"

CFLAGS = $(CCFLAGS) -I$(INCPATH)

\tw\twfont.exe: \
        ..\common\edisp.obj ..\common\hdisp.obj ..\common\adisp.obj \
        ..\common\grdetect.obj \
        ..\common\cwgrphc.obj ..\common\cwegrph.obj ..\common\cwagrph.obj \
        ..\common\ekbd.obj \
        ..\common\cscrn.obj ..\common\fileutil.obj ..\common\dir.obj \
        ..\common\sound.obj \
        getstr.obj tutil1.obj cufsetup.obj kbd.obj file.obj \
        fed.obj write.obj int.obj getch.obj popup.obj \
        fontmsg.obj convert.obj
    $(CC) -c ..\common\stampdate.c
    $(LINKER) $(LFLAGS) @scuf.tlr

getstr.obj: getstr.c var.h
    $(CC) $(CFLAGS) getstr.c

tutil1.obj: tutil1.c
    $(CC) $(CFLAGS) tutil1.c

cufsetup.obj: cufsetup.c var.h
    $(CC) $(CFLAGS) cufsetup.c

kbd.obj: kbd.c var.h
    $(CC) $(CFLAGS) kbd.c

file.obj: file.c
    $(CC) $(CFLAGS) file.c

fed.obj: fed.c
    $(CC) $(CFLAGS) fed.c

write.obj: write.c
    $(CC) $(CFLAGS) write.c

int.obj: int.c
    $(CC) $(CFLAGS) int.c

getch.obj: getch.c
    $(CC) $(CFLAGS) getch.c

popup.obj: popup.c
    $(CC) $(CFLAGS) popup.c

fontmsg.obj: fontmsg.c
    $(CC) $(CFLAGS) fontmsg.c

convert.obj: convert.c
    $(CC) $(CFLAGS) convert.c
