/****************************************************************************/
/*  INC.H 15 JAN 89                                                         */
/****************************************************************************/

#ifndef _INC_H
#define _INC_H

#include <stdio.h>
#include <stdlib.h>
#include <conio.h>
#include <dos.h>
#include <string.h>
#include <dir.h>
#include <bios.h>
#include <fcntl.h>
#include <sys\stat.h>
#include <process.h>
#include <ctype.h>
#include <errno.h>

#include "..\common\kbdcode.h"
#include "..\common\const.h"
#include "..\common\cwtype.h"
#include "..\common\proto.h"
#include "const.h"
#include "var.h"
#include "proto.h"

#endif /* _INC_H */
