#
# makefile for cw.exe
# Updated: Suttipong Kanakakorn
#          Sun  08-06-1989  16:25:44
#

!include "..\config.mak"

#INCPATH1 = ..\scuw\thaisyls
#CFLAGS = $(CCFLAGS) -I$(INCPATH);$(INCPATH1)
CFLAGS = $(CCFLAGS) -I$(INCPATH)

\tw\tw.exe: \
        ..\common\edisp.obj ..\common\hdisp.obj ..\common\adisp.obj \
        ..\common\grdetect.obj \
        ..\common\cwgrphc.obj ..\common\cwegrph.obj ..\common\cwagrph.obj \
        ..\common\ekbd.obj \
        ..\common\cscrn.obj ..\common\fileutil.obj ..\common\dir.obj \
        ..\common\sound.obj ..\common\cusong.obj \
        scrn.obj getstr.obj tutil1.obj edit.obj ins.obj del.obj \
        menu.obj \
        kbd.obj status.obj move.obj movement.obj wrap.obj \
        onscrn.obj file.obj search.obj block.obj cw.obj cwsetup.obj \
        mainsyls.obj thaieng.obj worewaan.obj findchar.obj horeheeb.obj \
        hunakad.obj julcut.obj karan.obj leadcon.obj \
        maimalai.obj maimuan.obj nopcut.obj nstrcmp.obj rorereo.obj \
        roreru.obj saraa.obj saraah.obj saraair.obj saraie.obj \
        sarao.obj sarar.obj sarau.obj saraue.obj sarauee.obj \
        saraum.obj global.obj
    $(CC) -c ..\common\stampdate.c
    $(LINKER) $(LFLAGS) @scuw.tlr

scrn.obj: scrn.c var.h
    $(CC) $(CFLAGS) scrn.c

getstr.obj: getstr.c var.h
    $(CC) $(CFLAGS) getstr.c

tutil1.obj: tutil1.c var.h
    $(CC) $(CFLAGS) tutil1.c

edit.obj: edit.c var.h
    $(CC) $(CFLAGS) edit.c

ins.obj: ins.c var.h
    $(CC) $(CFLAGS) ins.c

del.obj: del.c var.h
    $(CC) $(CFLAGS) del.c

menu.obj: menu.c var.h ..\common\cwgrphc.h
    $(CC) $(CFLAGS) menu.c

kbd.obj: kbd.c var.h
    $(CC) $(CFLAGS) kbd.c

status.obj:  status.c var.h
    $(CC) $(CFLAGS) status.c

move.obj: move.c var.h
    $(CC) $(CFLAGS) move.c

movement.obj: movement.c var.h
    $(CC) $(CFLAGS) movement.c

wrap.obj: wrap.c var.h
    $(CC) $(CFLAGS) wrap.c

onscrn.obj: onscrn.c var.h
    $(CC) $(CFLAGS) onscrn.c

file.obj: file.c var.h
    $(CC) $(CFLAGS) file.c

search.obj: search.c var.h
    $(CC) $(CFLAGS) search.c

block.obj: block.c var.h
    $(CC) $(CFLAGS) block.c

cw.obj: cw.c var.h ..\common\cwgrphc.h
    $(CC) $(CFLAGS) cw.c

cwsetup.obj: cwsetup.c var.h
    $(CC) $(CFLAGS) cwsetup.c

#
# Thai word separation
#

mainsyls.obj: mainsyls.c
    $(CC) $(CFLAGS) mainsyls.c
thaieng.obj: thaieng.c
    $(CC) $(CFLAGS) thaieng.c
worewaan.obj: worewaan.c
    $(CC) $(CFLAGS) worewaan.c
findchar.obj: findchar.c
    $(CC) $(CFLAGS) findchar.c
horeheeb.obj: horeheeb.c
    $(CC) $(CFLAGS) horeheeb.c
hunakad.obj: hunakad.c
    $(CC) $(CFLAGS) hunakad.c
julcut.obj: julcut.c
    $(CC) $(CFLAGS) julcut.c
karan.obj: karan.c
    $(CC) $(CFLAGS) karan.c
leadcon.obj: leadcon.c
    $(CC) $(CFLAGS) leadcon.c
maimalai.obj: maimalai.c
    $(CC) $(CFLAGS) maimalai.c
maimuan.obj: maimuan.c
    $(CC) $(CFLAGS) maimuan.c
nopcut.obj: nopcut.c
    $(CC) $(CFLAGS) nopcut.c
nstrcmp.obj: nstrcmp.c
    $(CC) $(CFLAGS) nstrcmp.c
rorereo.obj: rorereo.c
    $(CC) $(CFLAGS) rorereo.c
roreru.obj: roreru.c
    $(CC) $(CFLAGS) roreru.c
saraa.obj: saraa.c
    $(CC) $(CFLAGS) saraa.c
saraah.obj: saraah.c
    $(CC) $(CFLAGS) saraah.c
saraair.obj: saraair.c
    $(CC) $(CFLAGS) saraair.c
saraie.obj: saraie.c
    $(CC) $(CFLAGS) saraie.c
sarao.obj: sarao.c
    $(CC) $(CFLAGS) sarao.c
sarar.obj: sarar.c
    $(CC) $(CFLAGS) sarar.c
sarau.obj: sarau.c
    $(CC) $(CFLAGS) sarau.c
saraue.obj: saraue.c
    $(CC) $(CFLAGS) saraue.c
sarauee.obj: sarauee.c
    $(CC) $(CFLAGS) sarauee.c
saraum.obj: saraum.c
    $(CC) $(CFLAGS) saraum.c
global.obj: global.c
    $(CC) $(CFLAGS) global.c
