#
# makefile for cw.exe
# Updated: Suttipong Kanakakorn
#          Sun  08-06-1989  16:25:44
#

!include "..\config.mak"

INCPATH1 = ..\scuw\thaisep
CFLAGS = $(CCFLAGS) -I$(INCPATH);$(INCPATH1)

\tw\tw.exe: \
        ..\common\edisp.obj ..\common\hdisp.obj ..\common\adisp.obj \
        ..\common\grdetect.obj \
        ..\common\cwgrphc.obj ..\common\cwegrph.obj ..\common\cwagrph.obj \
        ..\common\ekbd.obj \
        ..\common\cscrn.obj ..\common\fileutil.obj ..\common\dir.obj \
        ..\common\sound.obj ..\common\cusong.obj \
        scrn.obj getstr.obj tutil1.obj edit.obj ins.obj del.obj \
        menu.obj \
        kbd.obj status.obj move.obj movement.obj wrap.obj \
        onscrn.obj file.obj search.obj block.obj cw.obj cwsetup.obj
    $(CC) -c ..\common\stampdate.c
    $(LINKER) $(LFLAGS) @scuw.tlr

scrn.obj: scrn.c var.h
    $(CC) $(CFLAGS) scrn.c

getstr.obj: getstr.c var.h
    $(CC) $(CFLAGS) getstr.c

tutil1.obj: tutil1.c var.h
    $(CC) $(CFLAGS) tutil1.c

edit.obj: edit.c var.h
    $(CC) $(CFLAGS) edit.c

ins.obj: ins.c var.h
    $(CC) $(CFLAGS) ins.c

del.obj: del.c var.h
    $(CC) $(CFLAGS) del.c

menu.obj: menu.c var.h ..\common\cwgrphc.h
    $(CC) $(CFLAGS) menu.c

kbd.obj: kbd.c var.h
    $(CC) $(CFLAGS) kbd.c

status.obj:  status.c var.h
    $(CC) $(CFLAGS) status.c

move.obj: move.c var.h
    $(CC) $(CFLAGS) move.c

movement.obj: movement.c var.h
    $(CC) $(CFLAGS) movement.c

wrap.obj: wrap.c var.h
    $(CC) $(CFLAGS) wrap.c

onscrn.obj: onscrn.c var.h
    $(CC) $(CFLAGS) onscrn.c

file.obj: file.c var.h
    $(CC) $(CFLAGS) file.c

search.obj: search.c var.h
    $(CC) $(CFLAGS) search.c

block.obj: block.c var.h
    $(CC) $(CFLAGS) block.c

cw.obj: cw.c var.h ..\common\cwgrphc.h
    $(CC) $(CFLAGS) cw.c

cwsetup.obj: cwsetup.c var.h
    $(CC) $(CFLAGS) cwsetup.c
