/*
    Routine.h
*/

#ifndef _ROUTINE_H
#define _ROUTINE_H

unsigned char *dummy();
unsigned char *Sara_UeeRtn();
unsigned char *Sara_ErWithoutTnl();
unsigned char *MaiMalaiRtn();
unsigned char *MaiMalaiFC();
unsigned char *Sara_ORtn();
unsigned char *Sara_AARtn();
unsigned char *LeadConRtn();
unsigned char *RoRuaRtn();
unsigned char *RuRtn();
unsigned char *Sara_ERtn();
unsigned char *Sara_ARtn();
unsigned char *Sara_AMRtn();
unsigned char *MaiTaiKhuRtn();
unsigned char *Sara_UuRtn();
unsigned char *Sara_IIRtn();
unsigned char *OAngRtn();
unsigned char *MaiHunAKatRtn();
unsigned char *KaranRtn();
unsigned char *MaiMuanRtn();
unsigned char *Sara_IRtn();
unsigned char *Sara_UeRtn();
unsigned char *Sara_URtn();
unsigned char *WoWaenRtn();
unsigned char *HoHipRtn();
unsigned char *CntlChar();
unsigned char *PuncChar();
unsigned char *TermChar();
unsigned char *FCPuncChar();
unsigned char *PaiYanNoiRtn();
unsigned char *MaiYamokRtn();
unsigned char *Sara_ORtn();
unsigned char *Sara_AeRtn();
unsigned char *Sara_AAWithoutTnl();
unsigned char *Sara_AAWithMaiTri();
unsigned char *Sara_AAWithTonal();

#endif /* _ROUTINE_H */
