/*
    Routine.h
*/

#ifndef _ROUTINE_H
#define _ROUTINE_H

/* hohip.c */
unsigned char *HoHipRtn(unsigned char *TempIndx);

/* hunakad.c */
unsigned char *MaiHunAKatRtn(register unsigned char *TempIndx);

/* julcut.c */
unsigned char *MaiTaiKhuRtn(unsigned char *TempIndx);
unsigned char *Sara_UuRtn(unsigned char *TempIndx);
unsigned char *Sara_IiRtn(unsigned char *TempIndx);

/* karan.c */
unsigned char *KaranRtn(unsigned char *TempIndx);

/* leadcon.c */
unsigned char *LeadConRtn(register unsigned char *TempIndx);

/* maimalai.c */
unsigned char *MaiMalaiRtn(register unsigned char *TempIndx);

/* maimuan.c */
unsigned char *MaiMuanRtn(unsigned char *TempIndx);

/* oang.c */
unsigned char *OAngRtn(unsigned char *TempIndx);

/* rorua.c */
unsigned char *RoRuaRtn(register unsigned char *TempIndx);

/* ru.c */
unsigned char *RuRtn(unsigned char *TempIndx);

/* saraa.c */
unsigned char *Sara_ARtn(register unsigned char *TempIndx);

/* saraaa.c */
unsigned char *Sara_AaRtn(register unsigned char *TempIndx);

/* saraae.c */
unsigned char *Sara_AeRtn(register unsigned char *TempIndx);

/* saraam.c */
unsigned char *Sara_AmRtn(register unsigned char *TempIndx);

/* sarae.c */
unsigned char *Sara_ERtn(unsigned char *TempIndx);

/* saraie.c */
unsigned char *Sara_IRtn(unsigned char *TempIndx);

/* sarao.c */
unsigned char *Sara_ORtn(register unsigned char *TempIndx);

/* sarau.c */
unsigned char *Sara_URtn(register unsigned char *TempIndx);

/* saraue.c */
unsigned char *Sara_UeRtn(unsigned char *TempIndx);

/* sarauue.c */
unsigned char *Sara_UeeRtn(register unsigned char *TempIndx);

/* wowaen.c */
unsigned char *WoWaenRtn(register unsigned char *TempIndx);

#endif /* _ROUTINE_H */
