/*
 * Thai Industrial Standard -- TIS 620-2529 (1986)
 * Naming convention as TISO proposed to ISO/ECMA for
 * draft ISO 8859-xx for Thailand.
 */

#ifndef _THAI_H
#define _THAI_H

#define KOKAI               0xA1    /* ก */
#define KHOKHAI             0xA2    /* ข */
#define KHOKHUAT            0xA3    /* ฃ */
#define KHOKHWAI            0xA4    /* ค */
#define KHOKHON             0xA5    /* ฅ */
#define KHORAKHANG          0xA6    /* ฆ */
#define NGONGU              0xA7    /* ง */
#define CHOCHAN             0xA8    /* จ */
#define CHOCHING            0xA9    /* ฉ */
#define CHOCHANG            0xAA    /* ช */
#define SOSO                0xAB    /* ซ */
#define CHOCHOE             0xAC    /* ฌ */
#define YOYING              0xAD    /* ญ */
#define DOCHADA             0xAE    /* ฎ */
#define TOPATAK             0xAF    /* ฏ */
#define THOTHAN             0xB0    /* ฐ */
#define THONANGMONTHO       0xB1    /* ฑ */
#define THOPHUTHAO          0xB2    /* ฒ */
#define NONEN               0xB3    /* ณ */
#define DODEK               0xB4    /* ด */
#define TOTAO               0xB5    /* ต */
#define THOTHUNG            0xB6    /* ถ */
#define THOTHAHAN           0xB7    /* ท */
#define THOTHONG            0xB8    /* ธ */
#define NONU                0xB9    /* น */
#define BOBAIMAI            0xBA    /* บ */
#define POPLA               0xBB    /* ป */
#define PHOPHUNG            0xBC    /* ผ */
#define FOFA                0xBD    /* ฝ */
#define PHOPHAN             0xBE    /* พ */
#define FOFAN               0xBF    /* ฟ */
#define PHOSAMPHAO          0xC0    /* ภ */
#define MOMA                0xC1    /* ม */
#define YOYAK               0xC2    /* ย */
#define RORUA               0xC3    /* ร */
#define RU                  0xC4    /* ฤ */
#define LOLING              0xC5    /* ล */
#define LU                  0xC6    /* ฦ */
#define WOWAEN              0xC7    /* ว */
#define SOSALA              0xC8    /* ศ */
#define SORUSI              0xC9    /* ษ */
#define SOSUA               0xCA    /* ส */
#define HOHIP               0xCB    /* ห */
#define LOCHULA             0xCC    /* ฬ */
#define OANG                0xCD    /* อ */
#define HONOKHUK            0xCE    /* ฮ */
#define PAIYANNOI           0xCF    /* ฯ */
#define SARA_A              0xD0    /* สระอะ */
#define MAIHUNAKAT          0xD1    /* ไม้หันอากาศ */
#define SARA_AA             0xD2    /* สระอา */
#define SARA_AM             0xD3    /* สระอำ */
#define SARA_I              0xD4    /* สระอิ */
#define SARA_II             0xD5    /* สระอี */
#define SARA_UE             0xD6    /* สระอึ */
#define SARA_UEE            0xD7    /* สระอือ */
#define SARA_U              0xD8    /* สระอุ */
#define SARA_UU             0xD9    /* สระอู */
#define PHINTHU             0xDA    /* . */
#define BAHT                0xDF    /* ฿ */
#define SARA_E              0xE0    /* สระเอ */
#define SARA_AE             0xE1    /* สระแอ */
#define SARA_O              0xE2    /* สระโอ */
#define MAIMUAN             0xE3    /* ไม้ม้วน */
#define MAIMALAI            0xE4    /* ไม้มลาย */
#define LAKKHANGYAO         0xE5    /* ลากข้างยาว */
#define MAIYAMOK            0xE6    /* ไม้ยมก */
#define MAITAIKHU           0xE7    /* ไม้ไต่คู้ */
#define MAIEK               0xE8    /* ไม้เอก */
#define MAITHO              0xE9    /* ไม้โท */
#define MAITRI              0xEA    /* ไม้ตรี */
#define MAICHATTAWA         0xEB    /* ไม้จัตวา */
#define THANTHAKHAT         0xEC    /* การันต์ */
#define NIKHAHIT            0xED    /* นิขหิต */
#define YAMAKKAN            0xEE    /* ยามักการ */
#define FONGMAN             0xEE    /* ฟองมัน */
#define THAIZERO            0xF0    /* ๐ */
#define THAIONE             0xF1    /* ๑ */
#define THAITWO             0xF2    /* ๒ */
#define THAITHREE           0xF3    /* ๓ */
#define THAIFOUR            0xF4    /* ๔ */
#define THAIFIVE            0xF5    /* ๕ */
#define THAISIX             0xF6    /* ๖ */
#define THAISEVEN           0xF7    /* ๗ */
#define THAIEIGHT           0xF8    /* ๘ */
#define THAININE            0xF9    /* ๙ */
#define ANGKHANHU           0xFA    /* อังคั่น */
#define KHOMUT              0xFB    /* โคมูตร */

/* Allow use of the symbol KARAN inplace of THANTHAKHAT */
#define KARAN               THANTHAKHAT

# endif _THAI_H
