# makefile for cuprint.exe
# by Suttipong Kanakakorn
# Sun  08-06-1989  16:24:05
#

!include "..\config.mak"

CFLAGS = $(CCFLAGS) -I$(INCPATH)

\tw\twprint.exe: \
        ..\common\edisp.obj ..\common\hdisp.obj ..\common\adisp.obj \
        ..\common\grdetect.obj \
        ..\common\cwgrphc.obj ..\common\cwegrph.obj ..\common\cwagrph.obj \
        ..\common\ekbd.obj \
        ..\common\cscrn.obj ..\common\fileutil.obj ..\common\dir.obj \
        ..\common\sound.obj \
        kbd.obj getstr.obj tutil1.obj cupsetup.obj \
        pmenu.obj smenu.obj prtutil.obj \
        printing.obj prt.obj prtt.obj prtg.obj \
        pic.obj dot.obj cpi.obj global.obj prncntrl.obj \
        error.obj preproc.obj 24pins.obj attr.obj cpthai.obj \
        prtbuf24.obj
    $(CC) -c ..\common\stampdate.c
    $(LINKER) $(LFLAGS) @scup.tlr

kbd.obj: kbd.c
    $(CC) $(CFLAGS) kbd.c

getstr.obj: getstr.c
    $(CC) $(CFLAGS) getstr.c

tutil1.obj: tutil1.c
    $(CC) $(CFLAGS) tutil1.c

cupsetup.obj: cupsetup.c
    $(CC) $(CFLAGS) cupsetup.c

pmenu.obj: pmenu.c
    $(CC) $(CFLAGS) pmenu.c

smenu.obj: smenu.c
    $(CC) $(CFLAGS) smenu.c

#pconfig.obj: pconfig.c
#    $(CC) $(CFLAGS) pconfig.c

prtutil.obj: prtutil.c
    $(CC) $(CFLAGS) prtutil.c

printing.obj: printing.c
    $(CC) $(CFLAGS) printing.c

prt.obj: prt.c
    $(CC) $(CFLAGS) prt.c

prtt.obj: prtt.c
    $(CC) $(CFLAGS) prtt.c

prtg.obj: prtg.c
    $(CC) $(CFLAGS) prtg.c

pic.obj: pic.c
    $(CC) $(CFLAGS) pic.c

dot.obj: dot.c
    $(CC) $(CFLAGS) dot.c

cpi.obj: cpi.c
    $(CC) $(CFLAGS) cpi.c

global.obj: global.c
    $(CC) $(CFLAGS) global.c

prncntrl.obj: prncntrl.c
    $(CC) $(CFLAGS) prncntrl.c

error.obj: error.c
    $(CC) $(CFLAGS) error.c

preproc.obj: preproc.c
    $(CC) $(CFLAGS) preproc.c

24pins.obj: 24pins.c
    $(CC) $(CFLAGS) 24pins.c

attr.obj: attr.c
    $(CC) $(CFLAGS) attr.c

cpthai.obj: cpthai.c
    $(CC) $(CFLAGS) cpthai.c

prtbuf24.obj: prtbuf24.c
    $(CC) $(CFLAGS) prtbuf24.c
