/****************************************************************************/
/*  Common MACRO for cw.exe and cuprint.exe
    Updated: Suttipong Kanakakorn
             Sun  08-06-1989  10:04:26                                      */
/****************************************************************************/

#ifndef _COMMON_CONST_H
#define _COMMON_CONST_H

#define BLANK               ' '
#define HUNAKADMITO         0xdb    /* treat as upper level */

#endif /* _COMMON_CONST_H */
