#
# makefile for common object file of cuprint.exe and cw.exe
# By Suttipong Kanakakorn
# Sun  08-06-1989  16:24:57
#
# TCC_OPTION -w = enable all warning
#
#

!include "..\config.mak"

CFLAGS = $(CCFLAGS) -I$(INCPATH)

project: edisp.obj hdisp.obj adisp.obj \
         grdetect.obj cwgrphc.obj cwegrph.obj cwagrph.obj \
         ekbd.obj cscrn.obj fileutil.obj dir.obj sound.obj cusong.obj

edisp.obj: edisp.asm cwfntm.asm
    $(ASM) $(AFLAGS) edisp.asm

hdisp.obj: hdisp.asm cwfnthm.asm
    $(ASM) $(AFLAGS) hdisp.asm

adisp.obj: adisp.asm cwfntam.asm
    $(ASM) $(AFLAGS) adisp.asm

grdetect.obj: grdetect.c grdetect.h
    $(CC) $(CFLAGS) grdetect.c

cwgrphc.obj: cwgrphc.c cwgrphc.h grdetect.h
    $(CC) $(CFLAGS) cwgrphc.c

cwegrph.obj: cwegrph.c cwgrphc.h
    $(CC) $(CFLAGS) cwegrph.c

cwagrph.obj: cwagrph.c cwgrphc.h
    $(CC) $(CFLAGS) cwagrph.c

ekbd.obj: ekbd.c
    $(CC) $(CFLAGS) ekbd.c

cscrn.obj: cscrn.c
    $(CC) $(CFLAGS) cscrn.c

fileutil.obj: fileutil.c
    $(CC) $(CFLAGS) fileutil.c

dir.obj: dir.c
    $(CC) $(CFLAGS) dir.c

sound.obj: sound.c
    $(CC) $(CFLAGS) sound.c

cusong.obj: cusong.c
    $(CC) $(CFLAGS) cusong.c
